swagger: "2.0"
info:
  version: "1.0.0"
  title: Cache Service
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
  - text/plain
paths:
  /v1/hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /v1/monitor:
    # binds a127 app logic to a route
    x-swagger-router-controller: monitor
    get:
      description: Returns status to the caller
      # used as the method name of the controller
      operationId: get
      parameters:
        - name: key
          in: query
          description: The key of the object to retrieved
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/APIResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/APIErrorResponse"
    post:
      description: Add object to monitor
      operationId: add
      parameters:
        - name: obj
          in: body
          description: Object to monitor
          required: true
          schema:
            $ref: '#/definitions/MonitorObjectSchema'
      responses:
        # responses may fall through to errors
        "500":
          description: Error
          schema:
            $ref: "#/definitions/APIErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  MonitorObjectSchema:
    properties:
      key:
        type: string
      value:
        type: string
  APIResponse:
    properties:
      message:
        type: string
  APIErrorResponse:
    properties:
      message:
        type: string
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
